### ISSUE TITLE
Index pages have double folder reference in URL

### ISSUE THREAD

**Issue by Drakohen** [TheStarport/KnowledgeBase#3]
Looks like on compile, the Index pages have a double folder reference for all links i.e. /DATA/DATA/Solar which breaks navigation. Other forms of navigation work i.e. Sidebar and Forward/Back options at the bottom of a page

**Comment by IrateRedKite** [comment]
I did a pass on the DATA index.md and this seems to be resolved now. To avoid this, link syntax should look something like `[Cockpits](./Cockpits/index.md)`
